import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
=======
import { ThemeProvider } from "../components/ThemeProvider";
import Container from "../components/layout/Container";
>>>>>>> dev
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "NARIMATO",
  description: "A real-time, card-based web application for dynamic image/text management and ranking",
  authors: [{ name: "moldovancsaba" }],
  keywords: ["Next.js", "React", "MongoDB", "Card System", "Ranking"],
>>>>>>> dev
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
  return (
=======
return (
>>>>>>> dev
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        {children}
=======
        <ThemeProvider>
          <Container>
            {children}
          </Container>
        </ThemeProvider>
>>>>>>> dev
      </body>
    </html>
  );
}
