name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Or the branch name you use

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_PRIVATE_KEY }}"
        channelId: live  # or any other channel you want to deploy to
        projectId: play-narimato